# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20181107_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.RemoveField(
            model_name='result',
            name='teacher',
        ),
    ]
