# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_result_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='service.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='service.Profile'),
        ),
    ]
