# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20181107_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.ForeignKey(default='7', on_delete=django.db.models.deletion.CASCADE, to='service.Faculty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='specialization',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='service.Specialization'),
            preserve_default=False,
        ),
    ]
